name: Deploy to render

on:
    push:
      branches: 
      - main
   
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: use Node.js 21.x
          uses: actions/setup-node@v2
          with:
            node-version: 21.x

        # Install deps
        - name: Install dependencies
          run: npm install
        
        # Run Build
        - name: Run Build
          run: npm run build

        # Run seed
        - name: Run seed
          run: npm run seed

        # Run develop
        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$DEPLOY_URL"
  