name: Test workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
# Operating system
    runs-on: ubuntu-latest

    steps:
    # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

        # Install dependencies
      - name: Install dependencies
        run: npm install

        # Run Build
      - name: Run Build
        run: npm run build

        # Run tests
      - name: Run tests
        run: npm run test-component
